### ISSUE TITLE
Getting a traceback on Windows 10, Python 3.11

### ISSUE THREAD

**Issue by jaybird110127** [vatsalaggarwal/whisper-cli#1]
I'm getting the following traceback when running Whisper under Windows 10 X64, Python 3.11. I don't know enough about what I'm doing to diagnose this.

Traceback (most recent call last) ────────────────────────────────┐
│ <frozen runpy>:198 in _run_module_as_main                                                        │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │   alter_argv = False                                                                         │ │
│ │         code = <code object <module> at 0x0000023F68465730, file                             │ │
│ │                "C:\python311\scripts\whisper.exe\__main__.py", line 1>                       │ │
│ │ main_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object "C:\python311\scripts\whisper.exe\">,   │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\python311\scripts\whisper.exe\">,                                         │ │
│ │                origin='C:\\python311\\scripts\\whisper.exe\\__main__.py'),                   │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__': 'C:\\python311\\scripts\\whisper.exe\\__main__.py',           │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\python311\\scripts\\whisper.exe\\__pycache__\\__main__.cpython-311.pyc', │ │
│ │                │   're': <module 're' from 'C:\\Python311\\Lib\\re\\__init__.py'>,           │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\python311\scripts\whisper.exe\">,                                         │ │
│ │                origin='C:\\python311\\scripts\\whisper.exe\\__main__.py')                    │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│ <frozen runpy>:88 in _run_code                                                                   │
│ ┌─────────────────────────────────────────── locals ───────────────────────────────────────────┐ │
│ │       cached = 'C:\\python311\\scripts\\whisper.exe\\__pycache__\\__main__.cpython-311.pyc'  │ │
│ │         code = <code object <module> at 0x0000023F68465730, file                             │ │
│ │                "C:\python311\scripts\whisper.exe\__main__.py", line 1>                       │ │
│ │        fname = 'C:\\python311\\scripts\\whisper.exe\\__main__.py'                            │ │
│ │ init_globals = None                                                                          │ │
│ │       loader = <zipimporter object "C:\python311\scripts\whisper.exe\">                      │ │
│ │     mod_name = '__main__'                                                                    │ │
│ │     mod_spec = ModuleSpec(name='__main__', loader=<zipimporter object                        │ │
│ │                "C:\python311\scripts\whisper.exe\">,                                         │ │
│ │                origin='C:\\python311\\scripts\\whisper.exe\\__main__.py')                    │ │
│ │     pkg_name = ''                                                                            │ │
│ │  run_globals = {                                                                             │ │
│ │                │   '__name__': '__main__',                                                   │ │
│ │                │   '__doc__': None,                                                          │ │
│ │                │   '__package__': '',                                                        │ │
│ │                │   '__loader__': <zipimporter object "C:\python311\scripts\whisper.exe\">,   │ │
│ │                │   '__spec__': ModuleSpec(name='__main__', loader=<zipimporter object        │ │
│ │                "C:\python311\scripts\whisper.exe\">,                                         │ │
│ │                origin='C:\\python311\\scripts\\whisper.exe\\__main__.py'),                   │ │
│ │                │   '__annotations__': {},                                                    │ │
│ │                │   '__builtins__': <module 'builtins' (built-in)>,                           │ │
│ │                │   '__file__': 'C:\\python311\\scripts\\whisper.exe\\__main__.py',           │ │
│ │                │   '__cached__':                                                             │ │
│ │                'C:\\python311\\scripts\\whisper.exe\\__pycache__\\__main__.cpython-311.pyc', │ │
│ │                │   're': <module 're' from 'C:\\Python311\\Lib\\re\\__init__.py'>,           │ │
│ │                │   ... +2                                                                    │ │
│ │                }                                                                             │ │
│ │  script_name = None                                                                          │ │
│ └──────────────────────────────────────────────────────────────────────────────────────────────┘ │
│                                                                                                  │
│ C:\python311\scripts\whisper.exe\__main__.py:7 in <module>                                       │
│                                                                                                  │
│ [Errno 2] No such file or directory: 'C:\\python311\\scripts\\whisper.exe\\__main__.py'          │
│                                                                                                  │
│ C:\Python311\Lib\site-packages\typer\main.py:328 in __call__                                     │
│                                                                                                  │
│ C:\Python311\Lib\site-packages\typer\main.py:311 in __call__                                     │
│                                                                                                  │
│ C:\Python311\Lib\site-packages\typer\main.py:350 in get_command                                  │
│                                                                                                  │
│ C:\Python311\Lib\site-packages\typer\main.py:332 in get_group                                    │
│                                                                                                  │
│ C:\Python311\Lib\site-packages\typer\main.py:483 in get_group_from_info                          │
│                                                                                                  │
│ C:\Python311\Lib\site-packages\typer\main.py:577 in get_command_from_info                        │
│                                                                                                  │
│ C:\Python311\Lib\site-packages\typer\main.py:553 in                                              │
│ get_params_convertors_ctx_param_name_from_function                                               │
│                                                                                                  │
│ C:\Python311\Lib\site-packages\typer\main.py:844 in get_click_param                              │
│                                                                                                  │
│ C:\Python311\Lib\site-packages\typer\main.py:773 in get_click_type                               │
└──────────────────────────────────────────────────────────────────────────────────────────────────┘
RuntimeError: Type not yet supported: str | None

**Comment by vatsalaggarwal** [comment]
You seem to be getting an error due to a change that was introduced in [PEP 604](https://peps.python.org/pep-0604/) which was introduced in Python 3.10, so indeed this should work with Python 3.11... really unsure why this is causing a problem for you...

Maybe the problem is `typer`? 
- How did you set up your environment? Did you use `poetry`?
- Can you send me the version numbers you're using perhaps using `pip freeze`? And I can help you diagnose?

By the way, how did you find this repo?

**Comment by quinncomendant** [comment]
Same here.

I'm on macOS 13.3 with python 3.11. I installed the venv like this:

```bash
❯ mkdir -p ~/tmp/whisper
❯ cd ~/tmp/whisper
❯ python -m venv .venv && source .venv/bin/activate && python -m pip install -U pip virtualenv whisper_cli
❯ which -a whisper
/Users/me/tmp/.venv/bin/whisper
```

Here's the error I get:

```
❯ whisper key set asdfasdfasdfasdfasdf
╭─────────────────────────────── Traceback (most recent call last) ────────────────────────────────╮
│ /Users/me/tmp/.venv/bin/whisper:8 in <module>                                                    │
│                                                                                                  │
│   5 from whisper_cli.main import app                                                             │
│   6 if __name__ == '__main__':                                                                   │
│   7 │   sys.argv[0] = re.sub(r'(-script\.pyw|\.exe)?$', '', sys.argv[0])                         │
│ ❱ 8 │   sys.exit(app())                                                                          │
│   9                                                                                              │
│                                                                                                  │
│ ╭─────────────────────────────────────────── locals ───────────────────────────────────────────╮ │
│ │ __annotations__ = {}                                                                         │ │
│ │    __builtins__ = <module 'builtins' (built-in)>                                             │ │
│ │      __cached__ = None                                                                       │ │
│ │         __doc__ = None                                                                       │ │
│ │        __file__ = '/Users/me/tmp/.venv/bin/whisper'                                          │ │
│ │      __loader__ = <_frozen_importlib_external.SourceFileLoader object at 0x102b8d8d0>        │ │
│ │        __name__ = '__main__'                                                                 │ │
│ │     __package__ = None                                                                       │ │
│ │        __spec__ = None                                                                       │ │
│ │             app = <typer.main.Typer object at 0x1045ca090>                                   │ │
│ │              re = <module 're' from                                                          │ │
│ │                   '/opt/homebrew/Cellar/python@3.11/3.11.2_1/Frameworks/Python.framework/Ve…│ │
│ │             sys = <module 'sys' (built-in)>                                                  │ │
│ ╰──────────────────────────────────────────────────────────────────────────────────────────────╯ │
│                                                                                                  │
│ /Users/me/tmp/.venv/lib/python3.11/site-packages/typer/main.py:328 in __call__                   │
│                                                                                                  │
│ /Users/me/tmp/.venv/lib/python3.11/site-packages/typer/main.py:311 in __call__                   │
│                                                                                                  │
│ /Users/me/tmp/.venv/lib/python3.11/site-packages/typer/main.py:350 in get_command                │
│                                                                                                  │
│ /Users/me/tmp/.venv/lib/python3.11/site-packages/typer/main.py:332 in get_group                  │
│                                                                                                  │
│ /Users/me/tmp/.venv/lib/python3.11/site-packages/typer/main.py:483 in get_group_from_info        │
│                                                                                                  │
│ /Users/me/tmp/.venv/lib/python3.11/site-packages/typer/main.py:577 in get_command_from_info      │
│                                                                                                  │
│ /Users/me/tmp/.venv/lib/python3.11/site-packages/typer/main.py:553 in                            │
│ get_params_convertors_ctx_param_name_from_function                                               │
│                                                                                                  │
│ /Users/me/tmp/.venv/lib/python3.11/site-packages/typer/main.py:844 in get_click_param            │
│                                                                                                  │
│ /Users/me/tmp/.venv/lib/python3.11/site-packages/typer/main.py:773 in get_click_type             │
╰──────────────────────────────────────────────────────────────────────────────────────────────────╯
RuntimeError: Type not yet supported: str | None
```

**Comment by vatsalaggarwal** [comment]
Thanks, have merged https://github.com/vatsalaggarwal/whisper-cli/pull/2 ... could you try again please?

**Comment by vatsalaggarwal** [comment]
@jaybird110127 / @quinncomendant I'm going to close this issue given the PR above... if you have any issues again, please feel free to reopen it. Appreciate you reporting this!
